saleor/saleor/account/urls.py
from django.conf.urls import url
from django.contrib.auth import views as django_views

from . import views

urlpatterns = [
    url(r"^$", views.details, name="details"),
    url(r"^login/$", views.login, name="login"),
    url(r"^logout/$", views.logout, name="logout"),
    url(r"^signup/$", views.signup, name="signup"),
    url(r"^password/reset/$", views.password_reset, name="reset-password"),
    url(
        r"^password/reset/done/$",
        django_views.PasswordResetDoneView.as_view(
            template_name="account/password_reset_done.html"
        ),
        name="reset-password-done",
    ),
    url(
        r"^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$",  # noqa
        views.password_reset_confirm,
        name="reset-password-confirm",
    ),
    url(
        r"password/reset/complete/$",
        django_views.PasswordResetCompleteView.as_view(  # noqa
            template_name="account/password_reset_from_key_done.html"
        ),
        name="reset-password-complete",
    ),
    url(r"^address/(?P<pk>\d+)/edit/$", views.address_edit, name="address-edit"),
    url(r"^address/(?P<pk>\d+)/delete/$", views.address_delete, name="address-delete"),
    url(r"^delete/$", views.account_delete, name="delete"),
    url(
        r"^(?P<token>[0-9A-Za-z_\-]+)/delete-confirm/",
        views.account_delete_confirm,
        name="delete-confirm",
    ),
]

saleor/saleor/dashboard/menu/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^$", views.menu_list, name="menu-list"),
    url(r"^add/$", views.menu_create, name="menu-add"),
    url(r"^(?P<pk>[0-9]+)/edit/$", views.menu_edit, name="menu-edit"),
    url(r"^(?P<pk>[0-9]+)/delete/$", views.menu_delete, name="menu-delete"),
    url(r"^(?P<pk>[0-9]+)/$", views.menu_details, name="menu-details"),
    url(r"^(?P<menu_pk>[0-9]+)/add/$", views.menu_item_create, name="menu-item-add"),
    url(
        r"^(?P<menu_pk>[0-9]+)/item/(?P<root_pk>[0-9]+)/add/$",
        views.menu_item_create,
        name="menu-item-add",
    ),
    url(
        r"^(?P<menu_pk>[0-9]+)/item/(?P<item_pk>[0-9]+)/edit/$",
        views.menu_item_edit,
        name="menu-item-edit",
    ),
    url(
        r"^(?P<menu_pk>[0-9]+)/item/(?P<item_pk>[0-9]+)/delete/$",
        views.menu_item_delete,
        name="menu-item-delete",
    ),
    url(
        r"^(?P<menu_pk>[0-9]+)/item/(?P<item_pk>[0-9]+)/$",
        views.menu_item_details,
        name="menu-item-details",
    ),
    url(
        r"^(?P<menu_pk>[0-9]+)/items/reorder/$",
        views.ajax_reorder_menu_items,
        name="menu-items-reorder",
    ),
    url(
        r"^(?P<menu_pk>[0-9]+)/item/(?P<root_pk>[0-9]+)/items/reorder/$",
        views.ajax_reorder_menu_items,
        name="menu-items-reorder",
    ),
    url(r"^ajax/links/$", views.ajax_menu_links, name="ajax-menu-links"),
]

saleor/saleor/dashboard/order/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^$", views.order_list, name="orders"),
    url(r"^add/$", views.order_create, name="order-create"),
    url(
        r"^(?P<order_pk>\d+)/create/$",
        views.create_order_from_draft,
        name="create-order-from-draft",
    ),
    url(r"^(?P<order_pk>\d+)/$", views.order_details, name="order-details"),
    url(r"^(?P<order_pk>\d+)/add-note/$", views.order_add_note, name="order-add-note"),
    url(r"^(?P<order_pk>\d+)/cancel/$", views.cancel_order, name="order-cancel"),
    url(
        r"^(?P<order_pk>\d+)/address/(?P<address_type>billing|shipping)/$",
        views.order_address,
        name="address-edit",
    ),
    url(
        r"^(?P<order_pk>\d+)/edit-customer/$",
        views.order_customer_edit,
        name="order-customer-edit",
    ),
    url(
        r"^(?P<order_pk>\d+)/remove-customer/$",
        views.order_customer_remove,
        name="order-customer-remove",
    ),
    url(
        r"^(?P<order_pk>\d+)/edit-shipping/$",
        views.order_shipping_edit,
        name="order-shipping-edit",
    ),
    url(
        r"^(?P<order_pk>\d+)/remove-shipping/$",
        views.order_shipping_remove,
        name="order-shipping-remove",
    ),
    url(
        r"^(?P<order_pk>\d+)/edit-discount/$",
        views.order_discount_edit,
        name="order-discount-edit",
    ),
    url(
        r"^(?P<order_pk>\d+)/edit-voucher/$",
        views.order_voucher_edit,
        name="order-voucher-edit",
    ),
    url(
        r"^(?P<order_pk>\d+)/remove-voucher/$",
        views.order_voucher_remove,
        name="order-voucher-remove",
    ),
    url(
        r"^(?P<order_pk>\d+)/delete/$",
        views.remove_draft_order,
        name="draft-order-delete",
    ),
    url(
        r"^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/capture/$",
        views.capture_payment,
        name="capture-payment",
    ),
    url(
        r"^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/void/$",
        views.void_payment,
        name="void-payment",
    ),
    url(
        r"^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/refund/$",
        views.refund_payment,
        name="refund-payment",
    ),
    url(
        r"^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/change/$",
        views.orderline_change_quantity,
        name="orderline-change-quantity",
    ),
    url(
        r"^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/cancel/$",
        views.orderline_cancel,
        name="orderline-cancel",
    ),
    url(
        r"^(?P<order_pk>\d+)/add-variant/$",
        views.add_variant_to_order,
        name="add-variant-to-order",
    ),
    url(
        r"^(?P<order_pk>\d+)/fulfill/$",
        views.fulfill_order_lines,
        name="fulfill-order-lines",
    ),
    url(
        r"^(?P<order_pk>\d+)/fulfillment/(?P<fulfillment_pk>\d+)/cancel/$",
        views.cancel_fulfillment,
        name="fulfillment-cancel",
    ),
    url(
        r"^(?P<order_pk>\d+)/fulfillment/(?P<fulfillment_pk>\d+)/tracking/$",
        views.change_fulfillment_tracking,
        name="fulfillment-change-tracking",
    ),
    url(
        r"^(?P<order_pk>\d+)/fulfillment/(?P<fulfillment_pk>\d+)/packing-slips/$",  # noqa
        views.fulfillment_packing_slips,
        name="fulfillment-packing-slips",
    ),
    url(r"^(?P<order_pk>\d+)/invoice/$", views.order_invoice, name="order-invoice"),
    url(
        r"^(?P<order_pk>\d+)/mark-as-paid/$",
        views.mark_order_as_paid,
        name="order-mark-as-paid",
    ),
    url(
        r"^(?P<order_pk>\d+)/ajax/shipping-methods/$",
        views.ajax_order_shipping_methods_list,
        name="ajax-order-shipping-methods",
    ),
]

saleor/saleor/dashboard/page/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^$", views.page_list, name="page-list"),
    url(r"^add/$", views.page_add, name="page-add"),
    url(r"^(?P<pk>[0-9]+)/$", views.page_details, name="page-details"),
    url(r"^(?P<pk>[0-9]+)/update/$", views.page_update, name="page-update"),
    url(r"^(?P<pk>[0-9]+)/delete/$", views.page_delete, name="page-delete"),
]

saleor/saleor/dashboard/sites/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^$", views.index, name="site-index"),
    url(r"^(?P<pk>\d+)/update/$", views.site_settings_edit, name="site-update"),
    url(r"^(?P<pk>\d+)/$", views.site_settings_details, name="site-details"),
    url(r"^(?P<pk>\d+)/delete/$", views.site_settings_edit, name="site-delete"),
    url(
        r"^(?P<site_settings_pk>\d+)/authorization_key/add/$",
        views.authorization_key_add,
        name="authorization-key-add",
    ),
    url(
        r"^(?P<site_settings_pk>\d+)/authorization_key/" r"(?P<key_pk>\d+)/update/$",
        views.authorization_key_edit,
        name="authorization-key-edit",
    ),
    url(
        r"^(?P<site_settings_pk>\d+)/authorization_key/" r"(?P<key_pk>\d+)/delete/$",
        views.authorization_key_delete,
        name="authorization-key-delete",
    ),
]

saleor/saleor/dashboard/urls.py
from django.conf.urls import include, url
from django.views.generic.base import TemplateView

from . import views as core_views
from .category.urls import urlpatterns as category_urls
from .collection.urls import urlpatterns as collection_urls
from .customer.urls import urlpatterns as customer_urls
from .discount.urls import urlpatterns as discount_urls
from .menu.urls import urlpatterns as menu_urls
from .order.urls import urlpatterns as order_urls
from .page.urls import urlpatterns as page_urls
from .product.urls import urlpatterns as product_urls
from .search.urls import urlpatterns as search_urls
from .shipping.urls import urlpatterns as shipping_urls
from .sites.urls import urlpatterns as site_urls
from .staff.urls import urlpatterns as staff_urls
from .taxes.urls import urlpatterns as taxes_urls

urlpatterns = [
    url(r"^$", core_views.index, name="index"),
    url(r"^categories/", include(category_urls)),
    url(r"^collections/", include(collection_urls)),
    url(r"^orders/", include(order_urls)),
    url(r"^page/", include(page_urls)),
    url(r"^products/", include(product_urls)),
    url(r"^customers/", include(customer_urls)),
    url(r"^staff/", include(staff_urls)),
    url(r"^discounts/", include(discount_urls)),
    url(r"^settings/", include(site_urls)),
    url(r"^menu/", include(menu_urls)),
    url(r"^shipping/", include(shipping_urls)),
    url(r"^style-guide/", core_views.styleguide, name="styleguide"),
    url(r"^search/", include(search_urls)),
    url(r"^taxes/", include(taxes_urls)),
    url(r"^next/", TemplateView.as_view(template_name="dashboard/next.html")),
]

saleor/saleor/search/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [url(r"^$", views.search, name="search")]

saleor/saleor/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve
from django.views.decorators.csrf import csrf_exempt
from django.views.i18n import JavaScriptCatalog, set_language

from .account.urls import urlpatterns as account_urls
from .checkout.urls import checkout_urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .dashboard.urls import urlpatterns as dashboard_urls
from .data_feeds.urls import urlpatterns as feed_urls
from .graphql.api import schema
from .graphql.views import GraphQLView
from .order.urls import urlpatterns as order_urls
from .page.urls import urlpatterns as page_urls
from .product.urls import urlpatterns as product_urls
from .search.urls import urlpatterns as search_urls

handler404 = "saleor.core.views.handle_404"

non_translatable_urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r"^dashboard/",
        include((dashboard_urls, "dashboard"), namespace="dashboard")),
    url(r"^graphql/", csrf_exempt(GraphQLView.as_view(schema=schema)),
        name="api"),
    url(
        r"^sitemap\.xml$",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    url(r"^i18n/$", set_language, name="set_language"),
    url("", include("social_django.urls", namespace="social")),
]

translatable_urlpatterns = [
    url(r"^", include(core_urls)),
    url(r"^checkout/",
        include((checkout_urls, "checkout"), namespace="checkout")),
    url(r"^jsi18n/$", JavaScriptCatalog.as_view(), name="javascript-catalog"),
    url(r"^order/", include((order_urls, "order"), namespace="order")),
    url(r"^page/", include((page_urls, "page"), namespace="page")),
    url(r"^products/", include((product_urls, "product"), namespace="product")),
    url(r"^account/", include((account_urls, "account"), namespace="account")),
    url(r"^feeds/", include((feed_urls, "data_feeds"), namespace="data_feeds")),
    url(r"^search/", include((search_urls, "search"), namespace="search")),
]

urlpatterns = non_translatable_urlpatterns + i18n_patterns(
    *translatable_urlpatterns)

if settings.DEBUG:
    try:
        import debug_toolbar
    except ImportError:
        """The debug toolbar was not installed. Ignore the error.
        settings.py should already have warned the user about it."""
    else:
        urlpatterns += [url(r"^__debug__/", include(debug_toolbar.urls))]

    urlpatterns += [
                       # static files (images, css, javascript, etc.)
                       url(r"^static/(?P<path>.*)$", serve)
                   ] + static("/media/", document_root=settings.MEDIA_ROOT)

if settings.ENABLE_SILK:
    urlpatterns += [url(r"^silk/", include("silk.urls", namespace="silk"))]

saleor/saleor/dashboard/search/forms.py
from ...search.backends import picker
from ...search.forms import SearchForm


class DashboardSearchForm(SearchForm):
    def search(self):
        query = self.cleaned_data["q"]
        search = picker.pick_dashboard_backend()
        return search(query)

saleor/saleor/dashboard/collection/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.urls import reverse
from django.utils.translation import pgettext_lazy
from django.views.decorators.http import require_POST

from ...core.utils import get_paginator_items
from ...menu.utils import get_menus_that_need_update, update_menus
from ...product.models import Collection
from ..views import staff_member_required
from .filters import CollectionFilter
from .forms import AssignHomepageCollectionForm, CollectionForm


@staff_member_required
@permission_required("product.manage_products")
def collection_list(request):
    site_settings = request.site.settings
    assign_homepage_col_form = AssignHomepageCollectionForm(
        request.POST or None, instance=site_settings
    )
    if request.method == "POST" and assign_homepage_col_form.is_valid():
        assign_homepage_col_form.save()
        msg = pgettext_lazy("Dashboard message", "Updated homepage collection")
        messages.success(request, msg)
        return redirect("dashboard:collection-list")
    collections = Collection.objects.prefetch_related("products").all()
    collection_filter = CollectionFilter(request.GET, queryset=collections)
    collections = get_paginator_items(
        collection_filter.qs, settings.DASHBOARD_PAGINATE_BY, request.GET.get("page")
    )
    ctx = {
        "collections": collections,
        "filter_set": collection_filter,
        "is_empty": not collection_filter.queryset.exists(),
        "assign_homepage_col_form": assign_homepage_col_form,
    }
    return TemplateResponse(request, "dashboard/collection/list.html", ctx)


@staff_member_required
@permission_required("product.manage_products")
def collection_create(request):
    collection = Collection()
    form = CollectionForm(
        request.POST or None, request.FILES or None, instance=collection
    )
    if form.is_valid():
        form.save()
        msg = pgettext_lazy("Collection message", "Added collection")
        messages.success(request, msg)
        return redirect("dashboard:collection-list")
    ctx = {"collection": collection, "form": form}
    return TemplateResponse(request, "dashboard/collection/detail.html", ctx)


@staff_member_required
@permission_required("product.manage_products")
def collection_update(request, pk=None):
    collection = get_object_or_404(Collection, pk=pk)
    form = CollectionForm(
        request.POST or None, request.FILES or None, instance=collection
    )
    if form.is_valid():
        collection = form.save()
        msg = pgettext_lazy("Collection message", "Updated collection")
        messages.success(request, msg)
        return redirect("dashboard:collection-update", pk=collection.pk)
    is_unpublish_restricted = (
        collection == request.site.settings.homepage_collection
        and collection.is_published
    )
    ctx = {
        "collection": collection,
        "form": form,
        "is_unpublish_restricted": is_unpublish_restricted,
    }
    return TemplateResponse(request, "dashboard/collection/detail.html", ctx)


@staff_member_required
@permission_required("product.manage_products")
def collection_delete(request, pk=None):
    collection = get_object_or_404(Collection, pk=pk)
    if request.method == "POST":
        menus = get_menus_that_need_update(collection=collection)
        collection.delete()
        if menus:
            update_menus(menus)
        msg = pgettext_lazy("Collection message", "Deleted collection")
        messages.success(request, msg)
        if request.is_ajax():
            response = {"redirectUrl": reverse("dashboard:collection-list")}
            return JsonResponse(response)
        return redirect("dashboard:collection-list")
    ctx = {"collection": collection}
    return TemplateResponse(request, "dashboard/collection/confirm_delete.html", ctx)


@require_POST
@staff_member_required
@permission_required("product.manage_products")
def collection_toggle_is_published(request, pk):
    collection = get_object_or_404(Collection, pk=pk)
    collection.is_published = not collection.is_published
    collection.save(update_fields=["is_published"])
    return JsonResponse({"success": True, "is_published": collection.is_published})

saleor/templates/dashboard/base.html
<!DOCTYPE html>
{% load static i18n %}
{% load render_bundle from webpack_loader %}
{% load version %}
{% load serialize_messages from utils %}

<html lang="{{ LANGUAGE_CODE }}" class="no-js">
  <head>
    <title>
      {% block title %}
        {% blocktrans trimmed context "Dashboard default page title" with site_name=site.name %}
          Dashboard - {{ site_name }}
        {% endblocktrans %}
      {% endblock %}
    </title>
    {% block meta %}
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
      <meta name="theme-color" content="#21915a" />
      <meta name="robots" content="noindex, nofollow">
    {% endblock meta %}

    {% include 'favicon.html' %}
    {% render_bundle 'dashboard' 'css' %}
    <link rel="stylesheet" type="text/css" href="{% static "versatileimagefield/css/versatileimagefield.css" %}">

    {% block custom_css %}{% endblock %}
  </head>

  <body class="{% block body_class %}body-home{% endblock %}">
    <header>
      <nav class="top-nav" id="top-nav">
        <div class="nav-wrapper">
          <div class="right">
            <ul id="user-action" class="dropdown-content">
              <li class="user-name">
                {{ request.user }}
              </li>
              <li class="divider"></li>
              <li>
                <a href="{% url 'home' %}" target="_blank" class="waves-effect">
                  {% trans "Visit storefront" context "Dashboard top navigation action" %}
                </a>
              </li>
              <li>
                <a href="{% url "dashboard:styleguide" %}" target="_blank" class="waves-effect">
                  {% trans "Style guide" context "Dashboard top navigation action" %}
                </a>
              </li>
              <li>
                <a href="{% url 'account:logout' %}" class="waves-effect">
                  {% trans "Log out" context "Dashboard top navigation action" %}
                </a>
              </li>
            </ul>
            <a class="dropdown-button" data-constrainwidth="false" href="#" data-activates="user-action">
              <svg data-src="{% static "dashboard/images/account-circle.svg" %}" width="24" height="24" fill="#fff" />
            </a>
            {% if SEARCH_IS_ENABLED %}
              <a href="{% url "dashboard:search" %}" class="dropdown-button hide-on-med-and-up" id="btn-search">
                <svg data-src="{% static "dashboard/images/search.svg" %}" width="24" height="24" fill="#fff" />
              </a>
            {% endif %}
          </div>
          <ul class="left">
            <li>
              <a href="#" id="toggle-menu">
                <svg data-src="{% static "dashboard/images/mobile-menu.svg" %}" width="24" height="24" />
              </a>
            </li>
            <li>
              <a href="{% url 'dashboard:index' %}" class="logo">
                <svg data-src="{% static "images/logo-white.svg" %}" height="38px" width="176px" />
              </a>
            </li>
            <li class="search">
              {% if SEARCH_IS_ENABLED %}
                <form method="get" action="{% url "dashboard:search" %}">
                  <a class="hide-on-med-and-up" id="btn-search-close"></a>
                  <div class="input-field d-inline">
                    <input id="search" type="search" placeholder="{% trans "Search" context "Dashboard search" %}" name="q" required value="{% if query %}{{ query }}{% endif %}">
                    <label class="hide-on-small-only">
                      <svg data-src="{% static "dashboard/images/search.svg" %}" width="24" height="24" fill="#fff" />
                    </label>
                  </div>
                  <a href="{% url "dashboard:search" %}" class="hide-on-med-and-up" id="btn-search-submit">
                    <svg data-src="{% static "dashboard/images/search.svg" %}" width="24" height="24" fill="#fff" />
                  </a>
                </form>
              {% endif %}
            </li>
          </ul>
          <ul class="side-nav">
            <li class="nav-home">
              <a href="{% url 'dashboard:index' %}">
                {% trans "Home" context "Dashboard homepage" %}
              </a>
            </li>
            {% if perms.product.manage_products %}
            <li class="side-nav-section" id="first">
              <p>
                {% trans "Catalogue" context "Dashboard catalogue" %}
              </p>
              <ul>
                  <li class="{% block menu_products_class %}{% endblock %}">
                    <a href="{% url 'dashboard:product-list' %}">
                      {% trans "Products" context "Dashboard products list" %}
                    </a>
                  </li>
                  <li class="{% block menu_categories_class %}{% endblock %}">
                    <a href="{% url 'dashboard:category-list' %}">
                      {% trans "Categories" context "Dashboard categories list" %}
                    </a>
                  </li>
                <li class="{% block menu_collections_class %}{% endblock %}">
                  <a href="{% url 'dashboard:collection-list' %}">
                    {% trans "Collections" context "Dashboard side navigation link" %}
                  </a>
                </li>
              </ul>
            </li>
            {% endif %}
            {% if perms.discount.manage_discounts %}
            <li class="side-nav-section">
              <p>
                {% trans "Discounts" context "Dashboard discounts list" %}
              </p>
              <ul>
                <li class="{% block menu_sales_class %}{% endblock %}">
                  <a href="{% url 'dashboard:sale-list' %}">
                    {% trans "Sales" context "Dashboard sales (discounts) list" %}
                  </a>
                </li>
                <li class="{% block menu_vouchers_class %}{% endblock %}">
                  <a href="{% url 'dashboard:voucher-list' %}">
                    {% trans "Vouchers" context "Dashboard vouchers list" %}
                  </a>
                </li>
              </ul>
            </li>
            {% endif %}
            {% if perms.order.manage_orders or perms.account.manage_users %}
            <li class="side-nav-section">
              <p>
                {% trans "Sales" context "Dashboard sales. `Sales' is noun of to sell" %}
              </p>
              <ul>
                {% if perms.order.manage_orders %}
                  <li class="{% block menu_orders_class %}{% endblock %}">
                    <a href="{% url 'dashboard:orders' %}">
                      {% trans "Orders" context "Dashboard orders list" %}
                    </a>
                  </li>
                {% endif %}
                {% if perms.account.manage_users %}
                  <li class="{% block menu_customers_class %}{% endblock %}">
                    <a href="{% url 'dashboard:customers' %}">
                      {% trans "Customers" context "Dashboard customers list" %}
                    </a>
                  </li>
                {% endif %}
              </ul>
            </li>
            {% endif %}
            {% if perms.account.manage_staff %}
              <li class="side-nav-section">
                <p>
                  {% trans "Staff management" context "Management section" %}
                </p>
                <ul>
                  <li class="{% block menu_staff_class %}{% endblock %}">
                    <a href="{% url 'dashboard:staff-list' %}">
                      {% trans "Staff members" context "Dashboard staff members list" %}
                    </a>
                  </li>
                </ul>
              </li>
            {% endif %}
            {% if perms.site.manage_settings or perms.shipping.manage_shipping or perms.product.manage_products or perms.page.manage_pages %}
              <li class="side-nav-section">
                <p>
                  {% trans "Configuration"  context "Dashboard configuration" %}
                </p>
                <ul>
                  {% if perms.product.manage_products %}
                    <li class="{% block menu_product_types_class %}{% endblock %}">
                      <a href="{% url 'dashboard:product-type-list' %}">
                        {% trans "Product types" context "Dashboard product types list" %}
                      </a>
                    </li>
                    <li class="{% block menu_attributes_class %}{% endblock %}">
                      <a href="{% url 'dashboard:attributes' %}">
                        {% trans "Attributes" context "Dashboard attributes list" %}
                      </a>
                    </li>
                  {% endif %}
                  {% if perms.shipping.manage_shipping %}
                    <li class="{% block menu_delivery_class %}{% endblock %}">
                      <a href="{% url 'dashboard:shipping-zone-list' %}">
                        {% trans "Shipping" context "Dashboard shipping zones list" %}
                      </a>
                    </li>
                  {% endif %}
                  {% if perms.menu.manage_menus %}
                    <li class="{% block menu_menus_class %}{% endblock %}">
                      <a href="{% url 'dashboard:menu-list' %}">
                        {% trans "Navigation" context "Dashboard menus list" %}
                      </a>
                    </li>
                  {% endif %}
                  {% if perms.site.manage_settings %}
                    <li class="{% block menu_settings_class %}{% endblock %}">
                      <a href="{% url 'dashboard:site-index' %}">
                        {% trans "Site settings" context "Dashboard site settings" %}
                      </a>
                    </li>
                  {% endif %}
                  <li class="{% block menu_taxes_class %}{% endblock %}">
                    <a href="{% url 'dashboard:taxes' %}">
                      {% trans "Taxes" context "Dashboard taxes" %}
                    </a>
                  </li>
                  {% if perms.page.manage_pages %}
                    <li class="{% block menu_pages_class %}{% endblock %}">
                      <a href="{% url 'dashboard:page-list' %}">
                        {% trans "Pages" context "Dashboard static pages" %}
                      </a>
                    </li>
                  {% endif %}
                </ul>
              </li>
              <li class="side-nav-section" id="version-indicator">
                <p>
                  {% trans "Release:" context "Dashboard software version" %} {% version %}
                </p>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </header>
    <div class="subheader top-nav">
      <div class="nav-wrapper container">
        {% block breadcrumbs %}
          <ul class="breadcrumbs">
            <li class="visible-s">
              <a href="#">
                {% trans "Home" context "Dashboard homepage" %}
              </a>
            </li>
          </ul>
        {% endblock %}
        {% block header_extra %}{% endblock %}
      </div>
    </div>
    <main class="main">
      <div id="base-modal" class="modal"></div>
      <div id="base-modal-fixed" class="modal modal-fixed-footer"></div>
      <div class="container">
        {% block content %}{% endblock %}
        <div id="dashboard-app"></div>
      </div>
    </main>
    <div id="messages-container" data-messages="{% serialize_messages %}"></div>

    <!-- Core Scripts - Include with every page -->
    <script type="text/javascript" src="{% url 'javascript-catalog' %}"></script>
    {% render_bundle 'dashboard' 'js' %}
    <script src="{% static "versatileimagefield/js/versatileimagefield.js" %}"></script>

    {% block custom_js %}{% endblock %}
  </body>
</html>