saleor/saleor/dashboard/product/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^$", views.product_list, name="product-list"),
    url(r"^(?P<pk>[0-9]+)/$", views.product_details, name="product-details"),
    url(
        r"^(?P<pk>[0-9]+)/publish/$",
        views.product_toggle_is_published,
        name="product-publish",
    ),
    url(
        r"^add/select-type/$", views.product_select_type, name="product-add-select-type"
    ),
    url(r"^add/(?P<type_pk>[0-9]+)/$", views.product_create, name="product-add"),
    url(r"^(?P<pk>[0-9]+)/update/$", views.product_edit, name="product-update"),
    url(r"^(?P<pk>[0-9]+)/delete/$", views.product_delete, name="product-delete"),
    url(r"^bulk-update/$", views.product_bulk_update, name="product-bulk-update"),
    url(r"^ajax/products/$", views.ajax_products_list, name="ajax-products"),
    url(r"^types/$", views.product_type_list, name="product-type-list"),
    url(r"^types/add/$", views.product_type_create, name="product-type-add"),
    url(
        r"^types/(?P<pk>[0-9]+)/update/$",
        views.product_type_edit,
        name="product-type-update",
    ),
    url(
        r"^types/(?P<pk>[0-9]+)/delete/$",
        views.product_type_delete,
        name="product-type-delete",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/$",
        views.variant_details,
        name="variant-details",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/variants/add/$",
        views.variant_create,
        name="variant-add",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/update/$",
        views.variant_edit,
        name="variant-update",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/delete/$",
        views.variant_delete,
        name="variant-delete",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/images/$",
        views.variant_images,
        name="variant-images",
    ),
    url(
        r"^ajax/variants/$",
        views.ajax_available_variants_list,
        name="ajax-available-variants",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/images/$",
        views.product_images,
        name="product-image-list",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/images/add/$",
        views.product_image_create,
        name="product-image-add",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/images/(?P<img_pk>[0-9]+)/$",
        views.product_image_edit,
        name="product-image-update",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/images/(?P<img_pk>[0-9]+)/delete/$",
        views.product_image_delete,
        name="product-image-delete",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/images/reorder/$",
        views.ajax_reorder_product_images,
        name="product-images-reorder",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/images/upload/$",
        views.ajax_upload_image,
        name="product-images-upload",
    ),
    url(r"attributes/$", views.attribute_list, name="attributes"),
    url(
        r"attributes/(?P<pk>[0-9]+)/$",
        views.attribute_details,
        name="attribute-details",
    ),
    url(r"attributes/add/$", views.attribute_create, name="attribute-add"),
    url(
        r"attributes/(?P<pk>[0-9]+)/update/$",
        views.attribute_edit,
        name="attribute-update",
    ),
    url(
        r"attributes/(?P<pk>[0-9]+)/delete/$",
        views.attribute_delete,
        name="attribute-delete",
    ),
    url(
        r"attributes/(?P<attribute_pk>[0-9]+)/value/add/$",
        views.attribute_value_create,
        name="attribute-value-add",
    ),
    url(
        r"attributes/(?P<attribute_pk>[0-9]+)/value/(?P<value_pk>[0-9]+)/update/$",  # noqa
        views.attribute_value_edit,
        name="attribute-value-update",
    ),
    url(
        r"attributes/(?P<attribute_pk>[0-9]+)/value/(?P<value_pk>[0-9]+)/delete/$",  # noqa
        views.attribute_value_delete,
        name="attribute-value-delete",
    ),
    url(
        r"attributes/(?P<attribute_pk>[0-9]+)/values/reorder/$",
        views.ajax_reorder_attribute_values,
        name="attribute-values-reorder",
    ),
]

saleor/saleor/product/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        r"^(?P<slug>[a-z0-9-_]+?)-(?P<product_id>[0-9]+)/$",
        views.product_details,
        name="details",
    ),
    url(
        r"^digital-download/(?P<token>[0-9A-Za-z_\-]+)/$",
        views.digital_product,
        name="digital-product",
    ),
    url(
        r"^category/(?P<slug>[a-z0-9-_]+?)-(?P<category_id>[0-9]+)/$",
        views.category_index,
        name="category",
    ),
    url(
        r"(?P<slug>[a-z0-9-_]+?)-(?P<product_id>[0-9]+)/add/$",
        views.product_add_to_checkout,
        name="add-to-checkout",
    ),
    url(
        r"^collection/(?P<slug>[a-z0-9-_/]+?)-(?P<pk>[0-9]+)/$",
        views.collection_index,
        name="collection",
    ),
]

saleor/saleor/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve
from django.views.decorators.csrf import csrf_exempt
from django.views.i18n import JavaScriptCatalog, set_language

from .account.urls import urlpatterns as account_urls
from .checkout.urls import checkout_urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .dashboard.urls import urlpatterns as dashboard_urls
from .data_feeds.urls import urlpatterns as feed_urls
from .graphql.api import schema
from .graphql.views import GraphQLView
from .order.urls import urlpatterns as order_urls
from .page.urls import urlpatterns as page_urls
from .product.urls import urlpatterns as product_urls
from .search.urls import urlpatterns as search_urls

handler404 = "saleor.core.views.handle_404"

non_translatable_urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r"^dashboard/",
        include((dashboard_urls, "dashboard"), namespace="dashboard")),
    url(r"^graphql/", csrf_exempt(GraphQLView.as_view(schema=schema)),
        name="api"),
    url(
        r"^sitemap\.xml$",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    url(r"^i18n/$", set_language, name="set_language"),
    url("", include("social_django.urls", namespace="social")),
]

translatable_urlpatterns = [
    url(r"^", include(core_urls)),
    url(r"^checkout/",
        include((checkout_urls, "checkout"), namespace="checkout")),
    url(r"^jsi18n/$", JavaScriptCatalog.as_view(), name="javascript-catalog"),
    url(r"^order/", include((order_urls, "order"), namespace="order")),
    url(r"^page/", include((page_urls, "page"), namespace="page")),
    url(r"^products/", include((product_urls, "product"), namespace="product")),
    url(r"^account/", include((account_urls, "account"), namespace="account")),
    url(r"^feeds/", include((feed_urls, "data_feeds"), namespace="data_feeds")),
    url(r"^search/", include((search_urls, "search"), namespace="search")),
]

urlpatterns = non_translatable_urlpatterns + i18n_patterns(
    *translatable_urlpatterns)

if settings.DEBUG:
    try:
        import debug_toolbar
    except ImportError:
        """The debug toolbar was not installed. Ignore the error.
        settings.py should already have warned the user about it."""
    else:
        urlpatterns += [url(r"^__debug__/", include(debug_toolbar.urls))]

    urlpatterns += [
                       # static files (images, css, javascript, etc.)
                       url(r"^static/(?P<path>.*)$", serve)
                   ] + static("/media/", document_root=settings.MEDIA_ROOT)

if settings.ENABLE_SILK:
    urlpatterns += [url(r"^silk/", include("silk.urls", namespace="silk"))]

saleor/saleor/product/views.py
import datetime
import json
import mimetypes
import os
from typing import Union

from django.http import (
    FileResponse,
    HttpResponseNotFound,
    HttpResponsePermanentRedirect,
    JsonResponse,
)
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.urls import reverse
from draftjs_sanitizer import SafeJSONEncoder

from ..checkout.utils import set_checkout_cookie
from ..core.utils import serialize_decimal
from ..seo.schema.product import product_json_ld
from .filters import ProductCategoryFilter, ProductCollectionFilter
from .models import Category, DigitalContentUrl
from .utils import (
    collections_visible_to_user,
    get_product_images,
    get_product_list_context,
    handle_checkout_form,
    products_for_checkout,
    products_for_products_list,
    products_with_details,
)
from .utils.attributes import get_product_attributes_data
from .utils.availability import get_product_availability
from .utils.digital_products import (
    digital_content_url_is_valid,
    increment_download_count,
)
from .utils.variants_picker import get_variant_picker_data


def product_details(request, slug, product_id, form=None):
    """Product details page.

    The following variables are available to the template:

    product:
        The Product instance itself.

    is_visible:
        Whether the product is visible to regular users (for cases when an
        admin is previewing a product before publishing).

    form:
        The add-to-checkout form.

    price_range:
        The PriceRange for the product including all discounts.

    undiscounted_price_range:
        The PriceRange excluding all discounts.

    discount:
        Either a Price instance equal to the discount value or None if no
        discount was available.

    local_price_range:
        The same PriceRange from price_range represented in user's local
        currency. The value will be None if exchange rate is not available or
        the local currency is the same as site's default currency.
    """
    products = products_with_details(user=request.user)
    product = get_object_or_404(products, id=product_id)
    if product.get_slug() != slug:
        return HttpResponsePermanentRedirect(product.get_absolute_url())
    today = datetime.date.today()
    is_visible = product.publication_date is None or product.publication_date <= today
    if form is None:
        form = handle_checkout_form(request, product, create_checkout=False)[0]
    availability = get_product_availability(
        product,
        discounts=request.discounts,
        country=request.country,
        local_currency=request.currency,
        extensions=request.extensions,
    )
    product_images = get_product_images(product)
    variant_picker_data = get_variant_picker_data(
        product,
        request.discounts,
        request.extensions,
        request.currency,
        request.country,
    )
    product_attributes = get_product_attributes_data(product)
    # show_variant_picker determines if variant picker is used or select input
    show_variant_picker = all([v.attributes for v in product.variants.all()])
    json_ld_data = product_json_ld(product, product_attributes)
    ctx = {
        "description_json": product.translated.description_json,
        "description_html": product.translated.description,
        "is_visible": is_visible,
        "form": form,
        "availability": availability,
        "product": product,
        "product_attributes": product_attributes,
        "product_images": product_images,
        "show_variant_picker": show_variant_picker,
        "variant_picker_data": json.dumps(
            variant_picker_data, default=serialize_decimal, cls=SafeJSONEncoder
        ),
        "json_ld_product_data": json.dumps(
            json_ld_data, default=serialize_decimal, cls=SafeJSONEncoder
        ),
    }
    return TemplateResponse(request, "product/details.html", ctx)


def digital_product(request, token: str) -> Union[FileResponse, HttpResponseNotFound]:
    """Return the direct download link to content if given token is still valid."""

    qs = DigitalContentUrl.objects.prefetch_related("line__order__user")
    content_url = get_object_or_404(qs, token=token)  # type: DigitalContentUrl
    if not digital_content_url_is_valid(content_url):
        return HttpResponseNotFound("Url is not valid anymore")

    digital_content = content_url.content
    digital_content.content_file.open()
    opened_file = digital_content.content_file.file
    filename = os.path.basename(digital_content.content_file.name)
    file_expr = 'filename="{}"'.format(filename)

    content_type = mimetypes.guess_type(str(filename))[0]
    response = FileResponse(opened_file)
    response["Content-Length"] = digital_content.content_file.size

    response["Content-Type"] = content_type
    response["Content-Disposition"] = "attachment; {}".format(file_expr)

    increment_download_count(content_url)
    return response


def product_add_to_checkout(request, slug, product_id):
    # types: (int, str, dict) -> None

    if not request.method == "POST":
        return redirect(
            reverse("product:details", kwargs={"product_id": product_id, "slug": slug})
        )

    products = products_for_checkout(user=request.user)
    product = get_object_or_404(products, pk=product_id)
    form, checkout = handle_checkout_form(request, product, create_checkout=True)
    if form.is_valid():
        form.save()
        if request.is_ajax():
            response = JsonResponse({"next": reverse("checkout:index")}, status=200)
        else:
            response = redirect("checkout:index")
    else:
        if request.is_ajax():
            response = JsonResponse({"error": form.errors}, status=400)
        else:
            response = product_details(request, slug, product_id, form)
    if not request.user.is_authenticated:
        set_checkout_cookie(checkout, response)
    return response


def category_index(request, slug, category_id):
    categories = Category.objects.prefetch_related("translations")
    category = get_object_or_404(categories, id=category_id)
    if slug != category.slug:
        return redirect(
            "product:category",
            permanent=True,
            slug=category.slug,
            category_id=category_id,
        )
    # Check for subcategories
    categories = category.get_descendants(include_self=True)
    products = (
        products_for_products_list(user=request.user)
        .filter(category__in=categories)
        .order_by("name")
        .prefetch_related("collections")
    )
    product_filter = ProductCategoryFilter(
        request.GET, queryset=products, category=category
    )
    ctx = get_product_list_context(request, product_filter)
    ctx.update({"object": category})
    return TemplateResponse(request, "category/index.html", ctx)


def collection_index(request, slug, pk):
    collections = collections_visible_to_user(request.user).prefetch_related(
        "translations"
    )
    collection = get_object_or_404(collections, id=pk)
    if collection.slug != slug:
        return HttpResponsePermanentRedirect(collection.get_absolute_url())
    products = (
        products_for_products_list(user=request.user)
        .filter(collections__id=collection.id)
        .order_by("name")
    )
    product_filter = ProductCollectionFilter(
        request.GET, queryset=products, collection=collection
    )
    ctx = get_product_list_context(request, product_filter)
    ctx.update({"object": collection})
    return TemplateResponse(request, "collection/index.html", ctx)

saleor/templates/dashboard/product/product_image/form.html
{% extends "dashboard/base.html" %}
{% load i18n %}
{% load materializecss %}
{% load static %}

{% block title %}
  {% if product_image.pk %}
    {% trans "Edit - Image" context "Image form text" %}
  {% else %}
    {% trans "Add image" context "Image form text" %}
  {% endif %} - {{ block.super }}
{% endblock %}

{% block body_class %}body-store body-products{% endblock %}

{% block menu_products_class %}active{% endblock %}

{% block header_menu %}
  {% url "dashboard:product-details" pk=product.pk as url %}
  {% include "dashboard/includes/_back_link.html" with url=url %}
{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs breadcrumbs--history">
    <li>
      <a href="{% url "dashboard:product-details" pk=product.pk %}" class="breadcrumbs--ellipsed-item">
        {{ product }}
      </a>
    </li>
    <li class="back-mobile">
      <a href="{% url "dashboard:product-details" pk=product.pk %}" class="breadcrumb">
        <svg data-src="{% static "dashboard/images/arrow-left.svg" %}" fill="#fff" width="20px" height="20px" />
      </a>
    </li>
    {% if product_image.pk %}
      <li>
        <span class="breadcrumbs--ellipsed-item">
          {% trans "Image" context "Image form text" %}
        </span>
      </li>
      <li>
        <span class="breadcrumbs--ellipsed-item">
          {% trans "Edit" context "Image form text" %}
        </span>
      </li>
    {% else %}
      <li>
        <span class="hide-on-med-and-down">
          {% trans "Add image" context "Image form breadcrumbs" %}
        </span>
        <span class="hide-on-large-only breadcrumbs--ellipsed-item">
          {% blocktrans trimmed context "Image form breadcrumbs"  %}
            Add image for {{ product }}
          {% endblocktrans %}
        </span>
      </li>
    {% endif %}
  </ul>
{% endblock %}

{% block menu_catalogue_class %} active{% endblock %}

{% block content %}
  <div class="row">
    <div class="col s12 l9">
      <div class="card">
        <form method="post" enctype="multipart/form-data">
          <div class="card-content">
            {% csrf_token %}
            <div class="row">
              {{ form.image|materializecss }}
            </div>
            <div class="row">
              {{ form.alt|materializecss }}
            </div>
          </div>
          <div class="card-action right-align">
            <a href="{% url "dashboard:product-image-list" product.pk %}" class="btn-flat waves-effect">
              {% trans "Cancel" context "Dashboard cancel action" %}
            </a>
            {% if product_image.pk %}
              <button type="submit" class="btn waves-effect">
                {% trans "Save" context "Dashboard update action" %}
              </button>
            {% else %}
              <button type="submit" class="btn waves-effect">
                {% trans "Create" context "Dashboard create action" %}
              </button>
            {% endif %}
          </div>
        </form>
      </div>
    </div>
    <div class="col s12 m3 help-box"></div>
  </div>
{% endblock %}

saleor/templates/dashboard/product/product_image/list.html
{% extends "dashboard/base.html" %}

{% load i18n %}
{% load static %}

{% block title %}
  {% trans "Images" %} - {{ block.super }}
{% endblock %}

{% block body_class %}body-products{% endblock %}

{% block menu_products_class %}active{% endblock %}

{% block header_extra %}
  <div class="btn-fab-fixed">
    <a class="btn-fab-default waves-effect waves-light"
       id="images-btn"
       href="{% url 'dashboard:product-image-add' product_pk=product.pk %}"
       title="{% trans "Add image" context "Add image button text" %}">
      <svg data-src="{% static "dashboard/images/add.svg" %}" />
    </a>
  </div>
{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs breadcrumbs--history">
    <li>
      <a href="{% url "dashboard:product-list" %}" class="breadcrumb">
        {% trans "Products" context "Dashboard products list" %}
      </a>
    </li>
    <li class="back-mobile">
      <a href="{% url "dashboard:product-list" %}">
        <svg data-src="{% static "dashboard/images/arrow-left.svg" %}" fill="#fff" width="20px" height="20px" />
      </a>
    </li>
    <li>
      <a href="{% url "dashboard:product-details" product.pk %}">{{ product }}</a>
    </li>
    <li>
      <span class="breadcrumbs--ellipsed-item">{% trans "Images" %}</span>
    </li>
  </ul>
{% endblock %}

{% block menu_catalogue_class %} active{% endblock %}

{% block content %}
  <div class="row">
    <div id="images" class="tab-content col s12 m9">
      <form action="{% url 'dashboard:product-images-upload' product_pk=product.pk %}" id="product-image-form" novalidate>
        <div class="dz-message"></div>
        {% csrf_token %}
        <div class="row">
          <ul class="product-gallery sortable-items" data-post-url="{% url 'dashboard:product-images-reorder' product_pk=product.pk %}" data-post-name="ordered_images">
            {% if images %}
              {% for image in images %}
                <li class="col s12 m6 l4 sortable-item"
                    data-id="{{ image.pk }}">
                  <div class="card">
                    <div class="card-image product-gallery-item-image">
                      <img class="responsive-img"
                           src="{{ image.image.thumbnail.255x255 }}"
                           srcset="{{ image.image.thumbnail.255x255 }} 1x, {{ image.image.thumbnail.510x510 }} 2x"
                           alt="">
                    </div>
                    <div class="card-content">
                      <span class="product-gallery-item-title card-title black-text" title="{{ image.alt }}">
                        {% if image.alt %}
                          {{ image.alt }}
                        {% else %}
                          <span class="grey-text">
                            {% trans "No description" context "Image card text" %}
                          </span>
                        {% endif %}
                      </span>
                    </div>
                    <div class="sortable__drag-area"></div>
                    <div class="card-action">
                      <a class="btn-flat waves-effect"
                         href="{% url 'dashboard:product-image-update' product_pk=product.pk img_pk=image.pk %}">
                        {% trans "Edit" context "Dashboard edit action" %}
                      </a>
                      <a href="#base-modal"
                         class="btn-flat waves-effect modal-trigger-custom"
                         data-href="{% url 'dashboard:product-image-delete' product_pk=product.pk img_pk=image.pk %}">
                        {% trans "Remove" context "Dashboard remove action" %}
                      </a>
                    </div>
                  </div>
                </li>
              {% endfor %}
            {% else %}
              <div class="sortable__drag-area"></div>
            {% endif %}
          </ul>
        <div class="col s12 m6 l4 product-gallery-item dropzone-message">
          <div class="row">
            <span class="product-gallery-item-title product-gallery-item-title--noclip card-title black-text">
              <span class="grey-text hide-on-med-and-down">
                {% trans "Drop images here to upload" context "Image gallery upload box text" %}
              </span>
            </span>
          </div>
        </div>
      </div>
      </form>
      <script type="application/template" id="template">
        <li class="col s12 m6 l4 product-gallery-item dz-preview dz-file-preview" data-id="{{ image.pk }}">
          <div class="card">
            <div class="card-image product-gallery-item-image">
              <img data-dz-thumbnail />
            </div>
            <div class="dz-progress">
              <span class="dz-upload" data-dz-uploadprogress></span>
            </div>
            <div class="card-content">
              <span class="product-gallery-item-title card-title black-text">
                <span class="grey-text">
                  {% trans "No description" context "Empty image gallery message" %}
                </span>
              </span>
            </div>
            <div class="sortable__drag-area"></div>
            <div class="card-action">
              <a class="btn-flat waves-effect card-action-edit" data-href-template="{% url 'dashboard:product-image-update' product_pk=product.pk img_pk=0 %}">
                {% trans "Edit" context "Dashboard edit action" %}
              </a>
              <a href="#base-modal" class="btn-flat waves-effect card-action-delete modal-trigger-custom"
              data-href-template="{% url 'dashboard:product-image-delete' product_pk=product.pk img_pk=0 %}">
                {% trans "Remove" context "Dashboard remove action" %}
              </a>
            </div>
            </div>
        </li>
      </script>
    </div>
  </div>
{% endblock %}

saleor/templates/dashboard/product/product_image/versatile_image.html
{% load i18n %}

{% if widget.is_initial %}
{% endif %}
<div class="sizedimage-mod preview">
  <label class="versatileimagefield-label">
    {% trans "Primary Point of Interest" %}
  </label>
  <p class="margin">
    {% trans "Pick the most relevant part of the image using the red circle." context "Image form text" %}
  </p>
  <div class="image-wrap outer">
    <div class="point-stage" id="{{ widget.point_stage_id }}" data-image_preview_id="{{ widget.image_preview_id }}">
      <div class="ppoi-point" id="{{ widget.ppoi_id }}"></div>
    </div>
    {% if widget.value %}
      <div class="image-wrap inner">
        <img src="{{ widget.sized_url }}" id="{{ widget.image_preview_id }}"
             data-hidden_field_id="{{ widget.hidden_field_id }}"
             data-point_stage_id="{{ widget.point_stage_id }}"
             data-ppoi_id="{{ widget.ppoi_id }}" class="sizedimage-preview"/>
      </div>
    {% endif %}
  </div>
</div>