saleor/saleor/dashboard/product/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^$", views.product_list, name="product-list"),
    url(r"^(?P<pk>[0-9]+)/$", views.product_details, name="product-details"),
    url(
        r"^(?P<pk>[0-9]+)/publish/$",
        views.product_toggle_is_published,
        name="product-publish",
    ),
    url(
        r"^add/select-type/$", views.product_select_type, name="product-add-select-type"
    ),
    url(r"^add/(?P<type_pk>[0-9]+)/$", views.product_create, name="product-add"),
    url(r"^(?P<pk>[0-9]+)/update/$", views.product_edit, name="product-update"),
    url(r"^(?P<pk>[0-9]+)/delete/$", views.product_delete, name="product-delete"),
    url(r"^bulk-update/$", views.product_bulk_update, name="product-bulk-update"),
    url(r"^ajax/products/$", views.ajax_products_list, name="ajax-products"),
    url(r"^types/$", views.product_type_list, name="product-type-list"),
    url(r"^types/add/$", views.product_type_create, name="product-type-add"),
    url(
        r"^types/(?P<pk>[0-9]+)/update/$",
        views.product_type_edit,
        name="product-type-update",
    ),
    url(
        r"^types/(?P<pk>[0-9]+)/delete/$",
        views.product_type_delete,
        name="product-type-delete",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/$",
        views.variant_details,
        name="variant-details",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/variants/add/$",
        views.variant_create,
        name="variant-add",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/update/$",
        views.variant_edit,
        name="variant-update",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/delete/$",
        views.variant_delete,
        name="variant-delete",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/images/$",
        views.variant_images,
        name="variant-images",
    ),
    url(
        r"^ajax/variants/$",
        views.ajax_available_variants_list,
        name="ajax-available-variants",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/images/$",
        views.product_images,
        name="product-image-list",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/images/add/$",
        views.product_image_create,
        name="product-image-add",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/images/(?P<img_pk>[0-9]+)/$",
        views.product_image_edit,
        name="product-image-update",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/images/(?P<img_pk>[0-9]+)/delete/$",
        views.product_image_delete,
        name="product-image-delete",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/images/reorder/$",
        views.ajax_reorder_product_images,
        name="product-images-reorder",
    ),
    url(
        r"^(?P<product_pk>[0-9]+)/images/upload/$",
        views.ajax_upload_image,
        name="product-images-upload",
    ),
    url(r"attributes/$", views.attribute_list, name="attributes"),
    url(
        r"attributes/(?P<pk>[0-9]+)/$",
        views.attribute_details,
        name="attribute-details",
    ),
    url(r"attributes/add/$", views.attribute_create, name="attribute-add"),
    url(
        r"attributes/(?P<pk>[0-9]+)/update/$",
        views.attribute_edit,
        name="attribute-update",
    ),
    url(
        r"attributes/(?P<pk>[0-9]+)/delete/$",
        views.attribute_delete,
        name="attribute-delete",
    ),
    url(
        r"attributes/(?P<attribute_pk>[0-9]+)/value/add/$",
        views.attribute_value_create,
        name="attribute-value-add",
    ),
    url(
        r"attributes/(?P<attribute_pk>[0-9]+)/value/(?P<value_pk>[0-9]+)/update/$",  # noqa
        views.attribute_value_edit,
        name="attribute-value-update",
    ),
    url(
        r"attributes/(?P<attribute_pk>[0-9]+)/value/(?P<value_pk>[0-9]+)/delete/$",  # noqa
        views.attribute_value_delete,
        name="attribute-value-delete",
    ),
    url(
        r"attributes/(?P<attribute_pk>[0-9]+)/values/reorder/$",
        views.ajax_reorder_attribute_values,
        name="attribute-values-reorder",
    ),
]

saleor/saleor/product/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        r"^(?P<slug>[a-z0-9-_]+?)-(?P<product_id>[0-9]+)/$",
        views.product_details,
        name="details",
    ),
    url(
        r"^digital-download/(?P<token>[0-9A-Za-z_\-]+)/$",
        views.digital_product,
        name="digital-product",
    ),
    url(
        r"^category/(?P<slug>[a-z0-9-_]+?)-(?P<category_id>[0-9]+)/$",
        views.category_index,
        name="category",
    ),
    url(
        r"(?P<slug>[a-z0-9-_]+?)-(?P<product_id>[0-9]+)/add/$",
        views.product_add_to_checkout,
        name="add-to-checkout",
    ),
    url(
        r"^collection/(?P<slug>[a-z0-9-_/]+?)-(?P<pk>[0-9]+)/$",
        views.collection_index,
        name="collection",
    ),
]

saleor/saleor/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve
from django.views.decorators.csrf import csrf_exempt
from django.views.i18n import JavaScriptCatalog, set_language

from .account.urls import urlpatterns as account_urls
from .checkout.urls import checkout_urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .dashboard.urls import urlpatterns as dashboard_urls
from .data_feeds.urls import urlpatterns as feed_urls
from .graphql.api import schema
from .graphql.views import GraphQLView
from .order.urls import urlpatterns as order_urls
from .page.urls import urlpatterns as page_urls
from .product.urls import urlpatterns as product_urls
from .search.urls import urlpatterns as search_urls

handler404 = "saleor.core.views.handle_404"

non_translatable_urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r"^dashboard/",
        include((dashboard_urls, "dashboard"), namespace="dashboard")),
    url(r"^graphql/", csrf_exempt(GraphQLView.as_view(schema=schema)),
        name="api"),
    url(
        r"^sitemap\.xml$",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    url(r"^i18n/$", set_language, name="set_language"),
    url("", include("social_django.urls", namespace="social")),
]

translatable_urlpatterns = [
    url(r"^", include(core_urls)),
    url(r"^checkout/",
        include((checkout_urls, "checkout"), namespace="checkout")),
    url(r"^jsi18n/$", JavaScriptCatalog.as_view(), name="javascript-catalog"),
    url(r"^order/", include((order_urls, "order"), namespace="order")),
    url(r"^page/", include((page_urls, "page"), namespace="page")),
    url(r"^products/", include((product_urls, "product"), namespace="product")),
    url(r"^account/", include((account_urls, "account"), namespace="account")),
    url(r"^feeds/", include((feed_urls, "data_feeds"), namespace="data_feeds")),
    url(r"^search/", include((search_urls, "search"), namespace="search")),
]

urlpatterns = non_translatable_urlpatterns + i18n_patterns(
    *translatable_urlpatterns)

if settings.DEBUG:
    try:
        import debug_toolbar
    except ImportError:
        """The debug toolbar was not installed. Ignore the error.
        settings.py should already have warned the user about it."""
    else:
        urlpatterns += [url(r"^__debug__/", include(debug_toolbar.urls))]

    urlpatterns += [
                       # static files (images, css, javascript, etc.)
                       url(r"^static/(?P<path>.*)$", serve)
                   ] + static("/media/", document_root=settings.MEDIA_ROOT)

if settings.ENABLE_SILK:
    urlpatterns += [url(r"^silk/", include("silk.urls", namespace="silk"))]

saleor/saleor/product/views.py
import datetime
import json
import mimetypes
import os
from typing import Union

from django.http import (
    FileResponse,
    HttpResponseNotFound,
    HttpResponsePermanentRedirect,
    JsonResponse,
)
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.urls import reverse
from draftjs_sanitizer import SafeJSONEncoder

from ..checkout.utils import set_checkout_cookie
from ..core.utils import serialize_decimal
from ..seo.schema.product import product_json_ld
from .filters import ProductCategoryFilter, ProductCollectionFilter
from .models import Category, DigitalContentUrl
from .utils import (
    collections_visible_to_user,
    get_product_images,
    get_product_list_context,
    handle_checkout_form,
    products_for_checkout,
    products_for_products_list,
    products_with_details,
)
from .utils.attributes import get_product_attributes_data
from .utils.availability import get_product_availability
from .utils.digital_products import (
    digital_content_url_is_valid,
    increment_download_count,
)
from .utils.variants_picker import get_variant_picker_data


def product_details(request, slug, product_id, form=None):
    """Product details page.

    The following variables are available to the template:

    product:
        The Product instance itself.

    is_visible:
        Whether the product is visible to regular users (for cases when an
        admin is previewing a product before publishing).

    form:
        The add-to-checkout form.

    price_range:
        The PriceRange for the product including all discounts.

    undiscounted_price_range:
        The PriceRange excluding all discounts.

    discount:
        Either a Price instance equal to the discount value or None if no
        discount was available.

    local_price_range:
        The same PriceRange from price_range represented in user's local
        currency. The value will be None if exchange rate is not available or
        the local currency is the same as site's default currency.
    """
    products = products_with_details(user=request.user)
    product = get_object_or_404(products, id=product_id)
    if product.get_slug() != slug:
        return HttpResponsePermanentRedirect(product.get_absolute_url())
    today = datetime.date.today()
    is_visible = product.publication_date is None or product.publication_date <= today
    if form is None:
        form = handle_checkout_form(request, product, create_checkout=False)[0]
    availability = get_product_availability(
        product,
        discounts=request.discounts,
        country=request.country,
        local_currency=request.currency,
        extensions=request.extensions,
    )
    product_images = get_product_images(product)
    variant_picker_data = get_variant_picker_data(
        product,
        request.discounts,
        request.extensions,
        request.currency,
        request.country,
    )
    product_attributes = get_product_attributes_data(product)
    # show_variant_picker determines if variant picker is used or select input
    show_variant_picker = all([v.attributes for v in product.variants.all()])
    json_ld_data = product_json_ld(product, product_attributes)
    ctx = {
        "description_json": product.translated.description_json,
        "description_html": product.translated.description,
        "is_visible": is_visible,
        "form": form,
        "availability": availability,
        "product": product,
        "product_attributes": product_attributes,
        "product_images": product_images,
        "show_variant_picker": show_variant_picker,
        "variant_picker_data": json.dumps(
            variant_picker_data, default=serialize_decimal, cls=SafeJSONEncoder
        ),
        "json_ld_product_data": json.dumps(
            json_ld_data, default=serialize_decimal, cls=SafeJSONEncoder
        ),
    }
    return TemplateResponse(request, "product/details.html", ctx)


def digital_product(request, token: str) -> Union[FileResponse, HttpResponseNotFound]:
    """Return the direct download link to content if given token is still valid."""

    qs = DigitalContentUrl.objects.prefetch_related("line__order__user")
    content_url = get_object_or_404(qs, token=token)  # type: DigitalContentUrl
    if not digital_content_url_is_valid(content_url):
        return HttpResponseNotFound("Url is not valid anymore")

    digital_content = content_url.content
    digital_content.content_file.open()
    opened_file = digital_content.content_file.file
    filename = os.path.basename(digital_content.content_file.name)
    file_expr = 'filename="{}"'.format(filename)

    content_type = mimetypes.guess_type(str(filename))[0]
    response = FileResponse(opened_file)
    response["Content-Length"] = digital_content.content_file.size

    response["Content-Type"] = content_type
    response["Content-Disposition"] = "attachment; {}".format(file_expr)

    increment_download_count(content_url)
    return response


def product_add_to_checkout(request, slug, product_id):
    # types: (int, str, dict) -> None

    if not request.method == "POST":
        return redirect(
            reverse("product:details", kwargs={"product_id": product_id, "slug": slug})
        )

    products = products_for_checkout(user=request.user)
    product = get_object_or_404(products, pk=product_id)
    form, checkout = handle_checkout_form(request, product, create_checkout=True)
    if form.is_valid():
        form.save()
        if request.is_ajax():
            response = JsonResponse({"next": reverse("checkout:index")}, status=200)
        else:
            response = redirect("checkout:index")
    else:
        if request.is_ajax():
            response = JsonResponse({"error": form.errors}, status=400)
        else:
            response = product_details(request, slug, product_id, form)
    if not request.user.is_authenticated:
        set_checkout_cookie(checkout, response)
    return response


def category_index(request, slug, category_id):
    categories = Category.objects.prefetch_related("translations")
    category = get_object_or_404(categories, id=category_id)
    if slug != category.slug:
        return redirect(
            "product:category",
            permanent=True,
            slug=category.slug,
            category_id=category_id,
        )
    # Check for subcategories
    categories = category.get_descendants(include_self=True)
    products = (
        products_for_products_list(user=request.user)
        .filter(category__in=categories)
        .order_by("name")
        .prefetch_related("collections")
    )
    product_filter = ProductCategoryFilter(
        request.GET, queryset=products, category=category
    )
    ctx = get_product_list_context(request, product_filter)
    ctx.update({"object": category})
    return TemplateResponse(request, "category/index.html", ctx)


def collection_index(request, slug, pk):
    collections = collections_visible_to_user(request.user).prefetch_related(
        "translations"
    )
    collection = get_object_or_404(collections, id=pk)
    if collection.slug != slug:
        return HttpResponsePermanentRedirect(collection.get_absolute_url())
    products = (
        products_for_products_list(user=request.user)
        .filter(collections__id=collection.id)
        .order_by("name")
    )
    product_filter = ProductCollectionFilter(
        request.GET, queryset=products, collection=collection
    )
    ctx = get_product_list_context(request, product_filter)
    ctx.update({"object": collection})
    return TemplateResponse(request, "collection/index.html", ctx)

saleor/templates/dashboard/product/attribute/detail.html
{% extends 'dashboard/base.html' %}

{% load i18n %}
{% load static %}

{% block title %}
  {{ attribute }} - {{ block.super }}
{% endblock %}

{% block body_class %}body-attribute{% endblock %}

{% block menu_attributes_class %}active{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs breadcrumbs--history">
    <li>
      <a href="{% url 'dashboard:attributes' %}" class="breadcrumbs--ellipsed-item">
      {% trans "Attributes" context "Attribute detail breadcrumbs" %}
      </a>
    </li>
    <li class="back-mobile">
      <a href="{% url 'dashboard:attributes' %}">
        <svg data-src="{% static "dashboard/images/arrow-left.svg" %}" fill="#fff" width="20px" height="20px" />
      </a>
    </li>
    <li>
      <span class="breadcrumbs--ellipsed-item">
        {{ attribute }}
      </span>
    </li>
  </ul>
{% endblock %}

{% block menu_catalogue_class %} active{% endblock %}

{% block content %}

  <div class="row">
    <div class="col s12 l9">
      <div class="card">
        <div class="card-content">
          <span class="card-title">
            {{ attribute.name }}
          </span>
          {% if product_type %}
            {% trans "Product type" %}: <a href="{% url "dashboard:product-type-update" pk=product_type.pk %}">{{ product_type }}</a>
          {% elif attribute.pk %}
            <a href="{% url "dashboard:product-type-list" %}">Assign to a product type</a>
          {% endif %}
        </div>
        <div class="card-action">
          <a class="btn-flat waves-effect" href="{% url "dashboard:attribute-update" attribute.pk %}">
            {% trans "Edit attribute" context "Attribute detail action" %}
          </a>
          <a class="btn-flat waves-effect modal-trigger-custom" href="#base-modal" data-href="{% url 'dashboard:attribute-delete' pk=attribute.pk %}">
            {% trans "Remove attribute" context "Attribute detail action" %}
          </a>
        </div>
      </div>
    </div>
    <div class="col s12 l9">
      <div class="card">
        <div class="card-content">
          <span class="card-title">{% trans "Attribute values" %}</span>
        </div>
        <div class="data-table-header-action">
          <a href="{% url 'dashboard:attribute-value-add' attribute_pk=attribute.pk %}" class="btn-flat waves-effect">
            {% trans "Add" %}
          </a>
        </div>
        <div class="data-table-container">
          <table class="bordered highlight responsive data-table">
            <thead>
              <tr>
                <th class="data-table-icon"></th>

                <th>{% trans "Display name" %}</th>
                <th></th>
              </tr>
            </thead>
            <tbody class="sortable-items" data-post-url="{% url 'dashboard:attribute-values-reorder' attribute_pk=attribute.pk %}" data-post-name="ordered_values">
              {% for value in values %}
                <tr class="sortable-item" data-id="{{ value.pk }}">
                  <td class="data-table-icon ignore-link sortable__drag-area">
                    <svg data-src="{% static "dashboard/images/reorder.svg" %}" height="20" width="20" fill="#000" />
                  </td>
                  <td>
                    {{ value.name }}
                  </td>
                  <td class="right-align">
                    <a href="{% url 'dashboard:attribute-value-update' attribute_pk=attribute.pk value_pk=value.pk %}" class="btn-flat waves-effect">
                      {% trans 'Edit' context 'Attribute value edit action' %}
                    </a>
                    <a class="btn-flat waves-effect modal-trigger-custom" href="#base-modal" data-href="{% url 'dashboard:attribute-value-delete' attribute_pk=attribute.pk value_pk=value.pk %}">
                      {% trans 'Remove' context 'Attribute value edit action' %}
                    </a>
                  </td>
                </tr>
              {% empty %}
                <tr>
                  <td colspan="2">{% trans "No attribute values" context "Empty list of attribute values" %}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

saleor/templates/dashboard/product/attribute/form.html
{% extends "dashboard/base.html" %}
{% load i18n %}
{% load materializecss %}
{% load static %}

{% block title %}
  {% if attribute.pk %}
   {% trans "Edit" context "Dashboard attributes list" %} - {{ attribute }}
  {% else %}
    {% trans "Add new attribute" context "Attribute detail page title" %}
  {% endif %}
  - {{ block.super }}
{% endblock %}

{% block body_class %}body-attributes{% endblock %}

{% block menu_attributes_class %}active{% endblock %}

{% block header_menu %}
  {% url "dashboard:attributes" as url %}
  {% include "dashboard/includes/_back_link.html" with url=url %}
{% endblock %}


{% block breadcrumbs %}
  <ul class="breadcrumbs breadcrumbs--history">
    <li>
      <a href="{% url 'dashboard:attributes' %}" class="breadcrumbs--ellipsed-item">
        {% trans "Attributes" context "Dashboard attributes list" %}
      </a>
    </li>
    <li class="back-mobile">
      <a href="{% url 'dashboard:attributes' %}">
        <svg data-src="{% static "dashboard/images/arrow-left.svg" %}" fill="#fff" width="20px" height="20px" />
      </a>
    </li>
    {% if attribute.pk %}
    <li>
      <a href="{% url 'dashboard:attribute-details' attribute.pk %}" class="breadcrumbs--ellipsed-item">
        {{ attribute }}
      </a>
    </li>
    <li>
      <span class="breadcrumbs--ellipsed-item">
        {% trans "Edit" context "Attribute detail breadcrumbs" %}
      </span>
    </li>
    {% else %}
    <li>
      <span class="breadcrumbs--ellipsed-item">
        {% trans "Add new attribute" context "Attribute detail breadcrumbs" %}
      </span>
    </li>
    {% endif %}
  </ul>
{% endblock %}

{% block menu_catalogue_class %} active{% endblock %}

{% block content %}
  <div class="row">
    <div class="col m12 l9">
      <div class="card">
        <form method="post" enctype="multipart/form-data" id="form-attributes" novalidate>
          <div class="card-content card-content-form">
            {% csrf_token %}
            <div class="row">
              {{ form.name|materializecss }}
            </div>
            <div class="row">
              {{ form.slug|materializecss }}
            </div>
          </div>
          <div class="card-action right-align">
            {% if attribute.pk %}
              <a href="{% url 'dashboard:attribute-details' attribute.pk %}" class="btn-flat waves-effect">
                {% trans "Cancel" context "Dashboard cancel action" %}
              </a>
              <button type="submit" class="btn waves-effect">
                {% trans "Save" context "Dashboard update action" %}
              </button>
            {% else %}
              <a href="{% url 'dashboard:attributes' %}" class="btn-flat waves-effect">
                {% trans "Cancel" context "Dashboard cancel action" %}
              </a>
              <button type="submit" class="btn waves-effect">
                {% trans "Create" context "Dashboard create action" %}
              </button>
            {% endif %}
          </div>
        </form>
      </div>
    </div>
    <div class="col m12 l3 help-box"></div>
  </div>
{% endblock %}

saleor/templates/dashboard/product/attribute/list.html
{% extends "dashboard/base.html" %}
{% load i18n %}
{% load materializecss %}
{% load static %}
{% load utils %}

{% block title %}
  {% trans "Attributes" context "Dashboard attributes list" %} - {{ block.super }}
{% endblock %}

{% block body_class %}body-attributes{% endblock %}

{% block menu_attributes_class %}active{% endblock %}

{% block header_extra %}
  <div class="btn-fab-fixed">
    <a class="btn-fab-default waves-effect waves-light" href="{% url 'dashboard:attribute-add' %}" title="{% trans "Add attribute" context "Attribute list add button text" %}">
      <svg data-src="{% static "dashboard/images/add.svg" %}" />
    </a>
  </div>
{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs">
    <li class="visible-s">
      {% trans "Attributes" context "Dashboard attributes list" %}
    </li>
  </ul>
{% endblock %}

{% block menu_catalogue_class %} active{% endblock %}

{% block content %}
  <div class="row">
    <div class="col s12 l9">
      {% if attributes %}
        <div class="card">
          <div class="data-table-container">
            <table class="bordered highlight data-table data-table-description">
              <thead>
                <tr>
                  {% trans "Name" context "Dashboard attributes list table header name" as label %}
                  {% sorting_header 'name' label %}
                  <th>{% trans "Product type" context "Name of product type related to the attribute" %}</th>
                  <th>
                    {% trans "Values" context "Dashboard attributes list table header values" %}
                  </th>
                </tr>
              </thead>
              <tbody>
                {% for pk, name, product_type, values in attributes %}
                  <tr data-action-go="{% url 'dashboard:attribute-details' pk=pk %}">
                    <td>
                      {{ name }}
                    </td>
                    <td>
                      {{ product_type|default:'-' }}
                    </td>
                    <td>
                      {% if values %}{{ values|join:", " }}{% else %}-{% endif %}
                    </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
        {% paginate attributes %}
      {% else %}
        {% if is_empty %}
          {% include 'dashboard/product/attribute/zero_page.html' %}
        {% else %}
          <div class="col s12">
            <div class="not-found">
              <p class="grey-text">
                {% trans "No attributes found." context "Empty attribute list message" %}
              </p>
            </div>
          </div>
        {% endif %}
      {% endif %}
    </div>
    <div class="col s12 l3" id="filters">
      {% if not is_empty %}{% filters filter_set %}{% endif %}
    </div>
  </div>
{% endblock %}

saleor/templates/dashboard/product/attribute/zero_page.html
{% extends 'dashboard/base_zero_page.html' %}
{% load i18n %}
{% load static %}

{% block title %}{% trans "No attributes found." %}{% endblock %}
{% block content %}
  {% static "dashboard/images/add.svg" as img_path %}
  {% blocktrans %}
    Attributes are used to define custom properties of products and variants, that can be used for filtering purposes in the storefront.<br>
    You can add attributes by using the <span class="btn-fab-presentation"><svg data-src="{{ img_path }}" /></span> button.
  {% endblocktrans %}
{% endblock %}